#!/usr/bin/env python3

import feedparser
from termcolor import colored
import sys
from subprocess import check_output
import re

if len(sys.argv) != 2:
    raise Exception("You must specify one atom")

out = check_output(["equery", "-qC", "list", sys.argv[1]]).decode("utf-8")
m = re.search(r"(.*/.*)-.*", str(out))

if m is None:
    raise Exception("Could not match any atom with your search")

rss = feedparser.parse("https://gitweb.gentoo.org/repo/gentoo.git/atom/{}?h=master".format(m.group(1)))
entrynr = 1

for i in rss['entries']:
        print(colored("[{}]".format(entrynr), 'red'), colored("{}".format(i.title), 'green'))
        for item in i.content:
            if item.type == "text/plain" and len(item.value):
                print(item.value)
        print("--------")
        entrynr += 1

