# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23

    - name: Build
      run: go build -v ./...
  gentoo-test:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3:systemd-20230320
      env:
        FEATURES: -ipc-sandbox -network-sandbox -pid-sandbox -sandbox -usersandbox
    steps:
      - uses: actions/checkout@v3
      - name: sync gentoo portage tree
        run: emerge-webrsync
      - name: install EIX and Go
        run: emerge --ask=n app-portage/eix dev-lang/go
      - name: initialize eix
        run: eix-update
      - name: Test
        run: go test -v ./...
